import NavBar from "./NavBar";

import styles from "./layout.module.css";
import "./global.css";

export const metadata = {
  title: "Create Next App!!!!!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className={styles.wrapper}>
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
