import { LayoutWrapper } from "./layout.styled";
import StyledComponentsRegistry from "./lib/registry";
import NavBar from "./NavBar";

export const metadata = {
  title: "Create Next App!!!!!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <LayoutWrapper>
            <NavBar />
            {children}
          </LayoutWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
